package mrapps;

import bean.KeyValue;
import java.util.ArrayList;

public class WordCount {


    /**
     * The map function is called once for each file of input.
     * @param content is the file's complete contents.
     * @return The return value is a ArrayList<KeyValue>.
     */
    public static ArrayList<KeyValue> map(StringBuffer content){
        // 自定义split方法: ArrayList<String> wordList = Util.contentSplit(content);
        String[] results = new String(content).split("\\s+|,|\\.|: |\\?|\'|\"|;|!|#|\\$|\\(|\\)|\\*|-|%|\\[|]");
        ArrayList<KeyValue> keyValues = new ArrayList<>();
        for (String word:results){
            KeyValue keyValue = new KeyValue(word, "1");
            keyValues.add(keyValue);
        }
        return keyValues;
    }


    /**
     * The reduce function is called once for each key generated by the map tasks.
     * @param values is a list of all the values created for that key by any map task.
     * @return values size.
     */
    public static int reduce(ArrayList<String> values){
        return values.size();
    }

}
